# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programimages',
            name='text',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
