# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_programimages_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programimages',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='programimages',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
