# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20161204_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programimages',
            old_name='images',
            new_name='image',
        ),
    ]
